version: '3.8'

services:
  # Aplicación Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravelservices_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_CONNECTION=mysql
      - DB_PORT=3306
      - DB_DATABASE=herzServices
      - DB_USERNAME=trazalem
      - DB_PASSWORD=Traz@lem2023

  # Nginx Web Server
  webserver:
    image: nginx:alpine
    container_name: laravelservices_webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  # MariaDB Database (more stable alternative to MySQL)
  db:
    image: 'mariadb:10.9'
    container_name: laravelservices_db
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: 'root_password'
      MARIADB_DATABASE: 'herzServices'
      MARIADB_USER: 'trazalem'
      MARIADB_PASSWORD: 'Traz@lem2023'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  # Redis (para caché y sesiones)
  redis:
    image: redis:alpine
    container_name: laravelservices_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

  # PhpMyAdmin (opcional, para gestionar la base de datos)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravelservices_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - laravel
    depends_on:
      - db

# Volumes para persistir datos
volumes:
  dbdata:
    driver: local

# Red personalizada
networks:
  laravel:
    driver: bridge